### PR TITLE
Added discord notification support

### PR DESCRIPTION
**Pull request by AntonyGarand**
Related to: https://github.com/LewisArdern/bXSS/issues/11

Added discord notifications

This requires the bot to already be on your server, and the channel name to be valid.

### CODE REVIEW

**Comment by LewisArdern** [comment]
Sorry iv'e been away on holiday, i'll review the commit tomorrow and let you know if i want to make some minor changes, overall you followed the structure perfectly with the validation check, etc.

**Comment by AntonyGarand** [comment]
The bot needs to have write permissions on the correct channel, but that's pretty much it.
In this case, I'm assuming the bot is already present and has the correct permissions, but that could be a future improvement: Generating the bot invite link (with correct permissions), warning if there is a missing permission, etc.

**Comment by LewisArdern** [comment]
We will need to update the README.md to reference what permissions it needs - otherwise there will be some new github issues with errors -- I can do that if you prefer

**Comment by AntonyGarand** [comment]
I'll update it, might take few days until I get the time though!

**Pull request merged**
